---
- name: Install romana post-install script
  template: src="romana-post-install.sh" dest="/var/tmp/romana-post-install.sh" mode=0755

- name: Execute romana post-install script
  shell: /var/tmp/romana-post-install.sh
  notify:
  - force restart kubernetes listener
