---
- name: force restart kubernetes listener
  command: systemctl reset-failed romana-kube-listener.service
  become: true
  become_user: root

- name: restart kubernetes listener
  command: service romana-kube-listener restart
  become: true
  become_user: root

